[auth]
redirect_uri = "Your-OIDC-URL"
cookie_secret = "Your-Cookie-Secret"
client_id = "Your-OIDC-Client-Id"
client_secret = "Your-OIDC-Client-Secret"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"

## Rename file to secrets.toml before use.